#%RAML 1.0 DataType
properties:
  ApplicationIdCode:
    description: code to specify the status of publishing file in external system
    example: "03"
    type: string
  DataTypeCode:
    description: The message returned to speciy the status
    type: string
    example: "ARG"
  TestType:
    description: The Correlation ID of the request
    type: string
    example: "T"
  ReceiverCode:
    description: The Correlation ID of the request
    type: string
    example: "00029472"
  SenderCode:
    description: The Correlation ID of the request
    type: string
    example: "000101"
  