#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    vrt:
      type: number
    line:
      type: number
    name:
      type: string
    unit:
      type: string
    amount:
      type: number
    price:
      type: number
    quantity:
      type: number
    c0:
      type: string
  
