#%RAML 1.0 ResourceType
uses:
  dataTypesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/datatypes-library/1.0.10/datatypes-library.raml
  traitsLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/traits-library/1.0.4/traits-library.raml
post?:
    displayName: Publish <<resourcePathName | !uppercamelcase | !singularize>> File
    description: This resource accepts the <<resourcePathName | !uppercamelcase>> File from SAP
    is:
      - traitsLib.hasAcceptEncoding
      - traitsLib.hasContentType
      - traitsLib.hasResponses
      - traitsLib.hasClientIdEnforcement
    body:
      multipart/form-data:
        type: dataTypesLib.EdiFile