#%RAML 1.0 DataType
type: object
properties:
  sid:
    type: string
  type:
    type: string
  idt:
    type: string
  form:
    type: string
  serial:
    type: string
  aun:
    type: number
  bname:
    type: string
  baddr:
    type: string
  btel:
    type: string
  paym:
    type: string
  curr:
    type: string
  exrt:
    type: number
  bacc:
    type: string
  bbank:
    type: string
  sumv:
    type: number
  sum:
    type: number
  vatv:
    type: number
  vat:
    type: number
  totalv:
    type: number
  total:
    type: number
  c0:
    type: string
  bcode:
    type: string
  type_ref:
    type: number
  stax:
    type: string
