#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    plant:
      description: plant code
      type: string
    serialNumber:
      description: Serial number for reference
      type: string
    materialNumber:
      description: Material Number
      type: string
      example: "T"
    actualQuantity:
      description: Actual Quantity
      type: number
    updateDate:
      description: The updated date
      type: string
    updateTime:
      description: The update time
      type: string
    slipNumber:
      description: Slip number
      type: string
    slipLine:
      description: Slip Line
      type: string
    productionOrder:
      description: Production Order
      type: string
    operationNumber:
      description: Operation Number
      type: string

  