#%RAML 1.0 DataType
properties:
  errorCode:
    description: code to specify the type of error
    example: 400
    type: number
  
  errorMessage:
    description: brief description of the error
    type: string
    example:
      "application/octet-stream is not one of the accepted MIME Types for the request body"

  errorType:
    description: classifies the type of the error
    type: string
    example: "BAD_REQUEST"
      
  correlationID:
    description: Correlation ID of the request
    type: string
    example: "28393680-805f-11ed-a40a-00059a3c7a00"
      
  timestamp:
    description: Timestamp of the transaction
    type: datetime 
    
      
