#%RAML 1.0 DataType
type: object
description: Datatype for SAP Outbound interfaces for NeoPM interaction which takes Control Indicator and Purchase Price files in .zip format along with EDI message header inforamtion.
properties:
  File1:   !include datatype-edi-file.raml
  File2:   !include datatype-edi-file.raml
  EDIMsgHeader: !include datatype-edi-msg-header.raml
  Transmissionheader: !include datatype-transmission-msg-header.raml