#%RAML 1.0 DataType
    properties:
      subsidiary:
        enum:
            - PAPVN-TL1
            - PAPVN-TL2
            - PMPC
        type: string
        example: PMPC
        description: The subsidiaries within SGST division
      externalSystem:
        enum: 
          - ICAST
          - RATIONALIZATION
          - ECITA
          - NEO_PM
          - SCM_NAVI
          - EPRO
          - IPS
          - PBS
          - CMS
          - E_INVOICE
          - SALES_EDI
        description: The name of the external system, to publish the file in
        type: string
        example: ICAST
      flatFileName:
        type: string
        example: FileName
        description: The name of the file to publish in external system
      flatFileFormat:
        enum:
            - CSV
            - TAB_DELIMITED
            - FIXED_WIDTH
        type: string
        example: CSV
        description: The format of the flat file to publish in external system
      flatFileExtension:
        type: string
        example: .dat
        description: the extension of the falt file to publish in external system
