#%RAML 1.0 Library
usage: Library of Resource types
resourceTypes:
  edifile_collection: !include resourceTypes/resourceType-edi-file-collection.raml
  edifilesap_collection: !include resourceTypes/resourceType-edi-file-sap-collection.raml
