#%RAML 1.0
title: SGST SD EDI EAPI
version: 1.0
description: Experience API to handle the Sales Distribution operations

uses:
  dataTypesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/datatypes-library/1.0.14/datatypes-library.raml
  traitsLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/traits-library/1.0.4/traits-library.raml
  resourceTypesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/resource-types-library/1.0.5/library-resource-types.raml
  securitySchemesLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/security-schemes-library/1.0.0/library-security-schemes.raml

#securedBy: [securitySchemesLib.oAuth2_0]
  
/fpl:
  displayName: fpl
  description: resource is used for accepting the FPL file from SAP and sending it to Sales EDI
  post:
  type: resourceTypesLib.edifile_collection
